weiAA/polls/urls.py
from django.conf.urls import patterns , url
from polls import views
from django.views.generic import DetailView,ListView
from polls.models import Poll
urlpatterns = patterns('',
	# url(r'^$',
	# 	ListView.as_view(
	# 		queryset = Poll.objects.order_by('pub_date')[:6],
	# 		context_object_name = 'latest_poll_list',
	# 		template_name = 'polls/index.html'
	# 		),
	# 	name = 'index',
	# 	),

	# url(r'^(?P<pk>\d+)/$',
	# 	DetailView.as_view(model=Poll,
	# 		template_name = 'polls/detail.html'
	# 		),
	# 	name = 'detail'
	# 	),

	# url(r'^(?P<pk>\d+)/result/$',
	# 	DetailView.as_view(
	# 		model = Poll,
	# 		template_name='polls/result.html'
	# 	),
	# 	name = 'result'
	# 	),

	# url(r'^(?P<poll_id>\d+)/vote/$',
	# 	'polls.views.vote',name = 'vote'),
	url(r'^$',views.index, name = 'index'),
	url(r'^(?P<poll_id>\d+)/$', views.details, name='detail'),
	url(r'^(?P<poll_id>\d+)/result/$',views.results, name='result'),
	url(r'^(?P<poll_id>\d+)/vote/$', views.vote, name = 'vote'),
)

weiAA/weiAA/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'weiAA.views.home', name='home'),
    # url(r'^weiAA/', include('weiAA.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^polls/', include('polls.urls',namespace = 'polls') ),
    url(r'^', include('weiaa_app.urls',namespace = 'weiAA_app')),
    url(r'^admin/', include(admin.site.urls)),
)

weiAA/polls/models.py
from django.db import models
import datetime
from django.utils import timezone

# Create your models here.
class Poll(models.Model):
	def __unicode__(self):

		return self.question
	
	def was_published_recently(self):

		return self.pub_date >= timezone.now() - datetime.timedelta(days = 1)

	question = models.CharField(max_length = 200)
	pub_date = models.DateTimeField('date published')

class Choice(models.Model):
	def __unicode__(self):
		return self.choice_text

	poll = models.ForeignKey(Poll)
	choice_text = models.CharField(max_length = 200)
	votes = models.IntegerField(default=0)

weiAA/polls/views.py
# Create your views here.
from django.http import HttpResponse,HttpResponseRedirect
from django.template import Context,loader
from polls.models import Poll,Choice
from django.shortcuts import get_object_or_404,render
from django.core.urlresolvers import reverse
def index(request):
	
	latest_poll_list = Poll.objects.order_by('pub_date')[:5]
	#output = ', '.join(p.question for p in latest_poll_list)
	template = loader.get_template('polls/index.html')
	context = Context({
		'latest_poll_list': latest_poll_list,
	})
	return HttpResponse(template.render(context))

def details(request,poll_id):
	poll = get_object_or_404(Poll, pk=poll_id)
	return render(request,'polls/detail.html',{'poll':poll})


def vote(request,poll_id):

	p= get_object_or_404(Poll, pk=poll_id)
	try:
		selected_choice = p.choice_set.get(pk=request.POST['choice'])
	except (KeyError , Choice.DoesNotExist):
		return render(request,'polls:detail',{'poll':p,'error_message':"You didn't select a choice.", })
	else:
		selected_choice.votes += 1
		selected_choice.save()
		return HttpResponseRedirect(reverse('polls:result', args=(p.id,)))


def results(request, poll_id):
	p = get_object_or_404(Poll,pk = poll_id)
	return render(request,'polls/result.html',{'poll':p })

weiAA/polls/templates/polls/detail.html
<html>
	<head>
		
	</head>
	<body>
		<h1>{{ poll.question }}</h1>
		{% if error_message %}<p><strong>{{ error_message }}</strong>{% endif %}
		<form action = "{% url 'polls:vote' poll.id %}" method = "post">
		{% csrf_token %}
		{% for choice in poll.choice_set.all %}	
			<input type = "radio" name="choice" id = "choice{{ forloop.counter}}" value="{{ choice.id}}">
			<label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
		{% endfor %}
		<input type = "submit" value="Vote" >
		</form>
		
	</body>
</html>

weiAA/polls/templates/polls/index.html
<html>
<head>
	
</head>
<body>
	<p>Hello!</p>
	{% if latest_poll_list %}
	<ul>
		{% for poll in latest_poll_list %}
		<li>
			<a href="{% url 'polls:detail' poll.id %}">{{poll.id}}: {{poll.question}}</a>
		</li>
		{% endfor %}
	</ul>
	{% else %}
	<p>No polls are available.</p>
	{% endif %}
</body>
</html>

weiAA/polls/templates/polls/result.html
<html>
	<head>
		
	</head>
	<body>
		<h1>{{ poll.question }}</h1>
		<ul>
			{% for choice in poll.choice_set.all %}
			<li>
				{{ choice.choice_text }} -- {{ choice.votes }} vote{{choice.votes|pluralize }}
			</li>
			{% endfor %}
		</ul>
		<a href = "{% url 'polls:detail' poll.id %}">Vote again?</a>
	</body>
</html>